server:
  port: 8082
spring:
  application:
    name: flow-eda-logger
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
logging:
  level:
    com.alibaba.nacos.common.remote.client: warn
