server:
  port: 8082
spring:
  application:
    name: flow-eda-logger
  rabbitmq:
    host: 10.0.4.17
    port: 5672
    username: guest
    password: guest
dubbo:
  application:
    name: flow-eda-logger
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    protocol: dubbo
    address: nacos://10.0.4.17:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 20883
logging:
  level:
    com.alibaba.nacos.common.remote.client: warn
