server:
  port: 8086
spring:
  application:
    name: flow-eda-oauth2
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/flow_eda_oauth2?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    hikari:
      max-lifetime: 60000
      connection-timeout: 10000
      validation-timeout: 3000
      maximum-pool-size: 10
      minimum-idle: 5
mybatis:
  type-handlers-package: com.flow.eda.web.mybatis
  configuration:
    map-underscore-to-camel-case: true
flow:
  oauth2:
    jwtSigningKey: flow-eda
    clientId: 1df7b0c1-3b28-40fb-aac0-148a14c7cba8
    clientSecret: zcUaT32GlwIjz4yBJjYZIIMvzf
    expired: 7200
    redirectUrl: http://localhost:8080/login