server:
  port: 8088
spring:
  application:
    name: flow-eda-runner
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456
    log_exchange: flow.log
    log_routing_key: flow.running.log
dubbo:
  application:
    name: flow-eda-runner
  registry:
    address: nacos://127.0.0.1:8848
    username: nacos
    password: nacos
  protocol:
    name: dubbo
    port: 20882
logging:
  level:
    com.alibaba.nacos.common.remote.client: warn
