server:
  port: 8088
spring:
  application:
    name: flow-eda-runner
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    log_exchange: flow.log
    log_routing_key: flow.running.log
